import type { DestinationTicket } from './types';

/** The 30 destination tickets from the original USA game. */
export const DESTINATION_TICKETS: DestinationTicket[] = [
  { id: 'boston-miami', from: 'boston', to: 'miami', points: 12 },
  { id: 'calgary-phoenix', from: 'calgary', to: 'phoenix', points: 13 },
  { id: 'calgary-saltlakecity', from: 'calgary', to: 'saltlakecity', points: 7 },
  { id: 'chicago-neworleans', from: 'chicago', to: 'neworleans', points: 7 },
  { id: 'chicago-santafe', from: 'chicago', to: 'santafe', points: 9 },
  { id: 'dallas-newyork', from: 'dallas', to: 'newyork', points: 11 },
  { id: 'denver-elpaso', from: 'denver', to: 'elpaso', points: 4 },
  { id: 'denver-pittsburgh', from: 'denver', to: 'pittsburgh', points: 11 },
  { id: 'duluth-elpaso', from: 'duluth', to: 'elpaso', points: 10 },
  { id: 'duluth-houston', from: 'duluth', to: 'houston', points: 8 },
  { id: 'helena-losangeles', from: 'helena', to: 'losangeles', points: 8 },
  { id: 'kansascity-houston', from: 'kansascity', to: 'houston', points: 5 },
  { id: 'losangeles-chicago', from: 'losangeles', to: 'chicago', points: 16 },
  { id: 'losangeles-miami', from: 'losangeles', to: 'miami', points: 20 },
  { id: 'losangeles-newyork', from: 'losangeles', to: 'newyork', points: 21 },
  { id: 'montreal-atlanta', from: 'montreal', to: 'atlanta', points: 9 },
  { id: 'montreal-neworleans', from: 'montreal', to: 'neworleans', points: 13 },
  { id: 'newyork-atlanta', from: 'newyork', to: 'atlanta', points: 6 },
  { id: 'portland-nashville', from: 'portland', to: 'nashville', points: 17 },
  { id: 'portland-phoenix', from: 'portland', to: 'phoenix', points: 11 },
  { id: 'sanfrancisco-atlanta', from: 'sanfrancisco', to: 'atlanta', points: 17 },
  { id: 'saultstmarie-nashville', from: 'saultstmarie', to: 'nashville', points: 8 },
  { id: 'saultstmarie-oklahomacity', from: 'saultstmarie', to: 'oklahomacity', points: 9 },
  { id: 'seattle-losangeles', from: 'seattle', to: 'losangeles', points: 9 },
  { id: 'seattle-newyork', from: 'seattle', to: 'newyork', points: 22 },
  { id: 'toronto-miami', from: 'toronto', to: 'miami', points: 10 },
  { id: 'vancouver-montreal', from: 'vancouver', to: 'montreal', points: 20 },
  { id: 'vancouver-santafe', from: 'vancouver', to: 'santafe', points: 13 },
  { id: 'winnipeg-houston', from: 'winnipeg', to: 'houston', points: 12 },
  { id: 'winnipeg-littlerock', from: 'winnipeg', to: 'littlerock', points: 11 },
];
